// 記事の単一情報源（Single Source of Truth）
// トップページのカード・関連記事・フッター・sitemap はすべてここを参照する。
// 記事を追加したら、このファイルに1件足すだけで全部に反映される。

export type CategoryId = "ramen" | "snacks" | "cafe" | "spot" | "prep";

export type Article = {
  slug: string;
  category: CategoryId;
  /** カード見出し＝記事タイトル（繁体字） */
  name: string;
  /** フッター等で使う短縮ラベル */
  shortLabel: string;
  desc: string;
  /** カード右上の地域ラベル */
  tag: string;
  emoji: string;
  image?: string;
  /** トップのエリアフィルタ用 */
  areas: string[];
  /** ISO date (YYYY-MM-DD) */
  published: string;
  updated: string;
  /**
   * 対価をいただいて制作したPR掲載記事なら true。
   * 景品表示法（いわゆるステマ規制）で広告である旨の明示が必要なので、
   * 記事ページ冒頭で PrLabel を出し、カードにもPRバッジを出す。
   * 未指定＝自主制作記事。既存記事はすべて未指定。
   */
  sponsored?: boolean;
};

export const ARTICLES: Article[] = [
  {
    slug: "noge",
    category: "ramen",
    name: "橫濱野毛續攤推薦2選｜平價居酒屋・壽司一貫¥99起🍶",
    shortLabel: "橫濱野毛續攤",
    desc: "櫻木町站徒步3分！霓虹中華酒場AM:PM＋全國釣魚直送的大眾壽司酒場，一人¥2,000〜3,000",
    tag: "神奈川",
    emoji: "🍶",
    image: "/noge/cover.jpg",
    areas: ["其他"],
    published: "2026-08-18",
    updated: "2026-08-18",
  },
  {
    slug: "tokyo-yakiniku",
    category: "ramen",
    name: "東京高級燒肉推薦｜叙々苑 品川王子大飯店店🥩",
    shortLabel: "東京高級燒肉",
    desc: "品川站徒步2分！日本高級燒肉代表，午餐¥2,640起就能吃到",
    tag: "東京",
    emoji: "🥩",
    image: "/tokyo-yakiniku/cover.jpg",
    areas: ["東京"],
    published: "2026-08-18",
    updated: "2026-08-18",
  },
  {
    slug: "shibuya-yakiniku",
    category: "ramen",
    name: "澀谷燒肉推薦｜ホルモン千葉・京都發跡的內臟燒肉名店🥩",
    shortLabel: "澀谷燒肉",
    desc: "獨創斜面鐵板收集肉汁！店員全程代烤，收尾炒烏龍麵必吃",
    tag: "東京",
    emoji: "🥩",
    image: "/shibuya-yakiniku/chiba-1.jpg",
    areas: ["東京"],
    published: "2026-07-31",
    updated: "2026-07-31",
  },
  {
    slug: "sanda-soba",
    category: "ramen",
    name: "兵庫三田蕎麥麵推薦｜蕎麦いち・關西手打蕎麥名店🍃",
    shortLabel: "三田蕎麥麵",
    desc: "神戶近郊隱藏名店！嚴選國產蕎麥粉的職人手打蕎麥",
    tag: "兵庫",
    emoji: "🍃",
    image: "/sanda-soba/soba1-1.jpg",
    areas: ["兵庫"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "nishinomiya-gardens",
    category: "ramen",
    name: "阪急西宮花園美食｜TOOTH TOOTH 蕎麥薄餅與甜點咖啡🍽️",
    shortLabel: "阪急西宮花園",
    desc: "西宮北口徒步3分！神戶甜點品牌的現煎蕎麥薄餅與季節水果可麗餅",
    tag: "兵庫",
    emoji: "🍽️",
    image: "/nishinomiya-gardens/tooth-1.jpg",
    areas: ["兵庫"],
    published: "2026-08-12",
    updated: "2026-08-12",
  },
  {
    slug: "conrad-osaka",
    category: "ramen",
    name: "大阪飯店自助餐推薦｜康萊德大阪 Atmos 40樓景觀buffet🥂",
    shortLabel: "大阪康萊德自助餐",
    desc: "地上200公尺的義式自助餐，挑高落地窗與水晶藝術裝置超好拍",
    tag: "大阪",
    emoji: "🥂",
    image: "/conrad-osaka/atmos-1.jpg",
    areas: ["大阪"],
    published: "2026-08-12",
    updated: "2026-08-12",
  },
  {
    slug: "osaka-gourmet",
    category: "ramen",
    name: "大阪美食推薦2選｜鐵板燒名店＆人氣居酒屋🍻",
    shortLabel: "大阪美食",
    desc: "鉄板屋な。＆酒場ビリー，大阪在地人氣的精緻晚餐＆夜遊居酒屋",
    tag: "大阪",
    emoji: "🍻",
    image: "/osaka-gourmet/teppan-1.jpg",
    areas: ["大阪"],
    published: "2026-07-01",
    updated: "2026-08-12",
  },
  {
    slug: "utsunomiya-gyoza",
    category: "ramen",
    name: "宇都宮餃子推薦2選｜兩大名店みんみん＆正嗣 對決🥟",
    shortLabel: "宇都宮餃子",
    desc: "1958年創業兩大巨頭！煎餃・水餃・炸餃CP值超高，餃子之都必吃",
    tag: "栃木",
    emoji: "🥟",
    image: "/utsunomiya-gyoza/minmin-1.jpg",
    areas: ["其他"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "ginza-apollo",
    category: "ramen",
    name: "銀座美食推薦｜THE APOLLO・希臘料理人氣餐廳🍽️",
    shortLabel: "銀座THE APOLLO",
    desc: "銀座必吃話題餐廳！地中海風味分享盤＆招牌烤起司料理",
    tag: "東京",
    emoji: "🍽️",
    image: "/ginza-apollo/apollo-1.jpg",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "futakotamagawa",
    category: "ramen",
    name: "二子玉川美食推薦5選｜芝麻街主題店・中華・甜點・精品咖啡🍽️",
    shortLabel: "二子玉川",
    desc: "芝麻街官方主題店・蒸籠中華・蘋果派・韓式屋台・精品咖啡，東京近郊散步美食",
    tag: "東京",
    emoji: "🍽️",
    image: "/futakotamagawa/sesame-1.jpg",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-09-03",
  },
  {
    slug: "kobe-gourmet",
    category: "ramen",
    name: "神戶美食推薦｜LA FAMIGLIA・元町的西西里料理專門店🍝",
    shortLabel: "神戶西西里料理",
    desc: "元町站徒步3分！日本少見的西西里料理與自然派葡萄酒，午餐¥2,500起",
    tag: "兵庫",
    emoji: "🍝",
    image: "/kobe-gourmet/famiglia-1.jpg",
    areas: ["兵庫"],
    published: "2026-09-04",
    updated: "2026-09-04",
  },
  {
    slug: "steak-zen",
    category: "ramen",
    name: "神戶牛推薦｜ステーキハウスZEN 三宮店・A5鐵板燒名店🥩",
    shortLabel: "神戶牛ZEN",
    desc: "神戶必吃A5神戶牛鐵板燒名店，主廚現煎入口即化",
    tag: "兵庫",
    emoji: "🥩",
    image: "/steak-zen/zen-1.jpg",
    areas: ["兵庫"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "ramen",
    category: "ramen",
    name: "東京拉麵推薦6選｜必吃排隊名店・柚子鹽・家系🍜",
    shortLabel: "東京拉麵推薦",
    desc: "三軒茶屋無招牌名店めん和正・和利道・俺流鹽味・台場神仙・AFURI柚子鹽・町田商店",
    tag: "東京",
    emoji: "🍜",
    image: "/ramen/washo-1.jpg",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-08-12",
  },
  {
    slug: "kansai-ramen",
    category: "ramen",
    name: "關西拉麵推薦｜大阪必吃濃厚魚介沾麵・つじ田🍜",
    shortLabel: "關西拉麵推薦",
    desc: "大阪肥後橋名店つじ田的濃厚魚介沾麵，加檸檬與黑七味變化風味",
    tag: "大阪",
    emoji: "🍜",
    image: "/kansai-ramen/tsujita-2.jpg",
    areas: ["大阪"],
    published: "2026-07-31",
    updated: "2026-07-31",
  },
  {
    slug: "shin-okubo",
    category: "ramen",
    name: "新大久保美食推薦｜韓國料理・咖啡・甜點食べ歩き🇰🇷",
    shortLabel: "新大久保",
    desc: "ナッコプセ鍋・韓系咖啡廳・ドバイ餅，實際走訪3間必去",
    tag: "東京",
    emoji: "🍲",
    image: "/shin-okubo/sawee-1.jpg",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-08-12",
  },
  {
    slug: "takeout-cake",
    category: "snacks",
    name: "東京外帶蛋糕推薦｜PARIYA・IG爆紅杯型鮮奶油蛋糕🍰",
    shortLabel: "東京外帶蛋糕",
    desc: "澀谷車站直結B2！草莓經典款¥1,058起，帶回飯店當宵夜的最強選擇",
    tag: "東京",
    emoji: "🍰",
    image: "/takeout-cake/cover.jpg",
    areas: ["東京"],
    published: "2026-08-18",
    updated: "2026-08-18",
  },
  {
    slug: "mister-donut",
    category: "snacks",
    name: "Mister Donut期間限定推薦｜日本ミスド的季節限定甜甜圈🍩",
    shortLabel: "Mister Donut",
    desc: "秋季地瓜甜甜圈全5款¥183起、波堤×布丁話題新品，日本才有的季節限定",
    tag: "日本",
    emoji: "🍩",
    image: "/mister-donut/motchurin-1.jpg",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-09-04",
  },
  {
    slug: "tokyo-cookies",
    category: "snacks",
    name: "東京伴手禮推薦｜高級手工餅乾・必買甜點🍪",
    shortLabel: "東京手工餅乾",
    desc: "奧地利認證大師的手工餅乾禮盒，需預約的超人氣伴手禮",
    tag: "東京",
    emoji: "🍪",
    image: "/tokyo-cookies/kayanuma-1.jpg",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "gakugeidaigaku-cafe",
    category: "cafe",
    name: "學藝大學咖啡廳推薦｜Bubbles Chill・開放式吐司與精品咖啡☕",
    shortLabel: "學藝大學咖啡",
    desc: "學藝大學站徒步4分！酪梨鮮蝦開放式吐司與精品咖啡，早上8點開門的極簡咖啡廳",
    tag: "東京",
    emoji: "☕",
    image: "/gakugeidaigaku-cafe/bubbles-1.jpg",
    areas: ["東京"],
    published: "2026-09-03",
    updated: "2026-09-03",
  },
  {
    slug: "kiyosumi-cafe",
    category: "cafe",
    name: "清澄白河咖啡廳推薦2選｜B² ＆ iki Roastery・東京咖啡聖地☕",
    shortLabel: "清澄白河咖啡",
    desc: "麵包工廠×咖啡烘焙廠的 B²，隅田川旁倉庫改建的 iki，兩間都早上開門",
    tag: "東京",
    emoji: "☕",
    image: "/kiyosumi-cafe/iki-1.jpg",
    areas: ["東京"],
    published: "2026-07-31",
    updated: "2026-07-31",
  },
  {
    slug: "ikejiri-cafe",
    category: "cafe",
    name: "池尻大橋咖啡廳推薦｜UN LIVRE・澀谷一站的法式甜點名店🍓",
    shortLabel: "池尻大橋咖啡",
    desc: "澀谷搭車一站直達！當季水果蛋糕＆夏季限定刨冰，寵物友善露台座位",
    tag: "東京",
    emoji: "🍓",
    image: "/ikejiri-cafe/unlivre-1.jpg",
    areas: ["東京"],
    published: "2026-07-31",
    updated: "2026-07-31",
  },
  {
    slug: "shibuya-cafe",
    category: "cafe",
    name: "澀谷咖啡廳推薦｜RECOCO レココ・黑膠唱片試聽咖啡🎵",
    shortLabel: "澀谷咖啡",
    desc: "澀谷必去！可親手試聽黑膠唱片的音樂體驗咖啡，約300張唱片聽到飽",
    tag: "東京",
    emoji: "🎵",
    image: "/shibuya-cafe/recoco-1.jpg",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "bolt-uehara",
    category: "cafe",
    name: "代代木上原咖啡廳推薦｜BOLT・寵物友善人氣店☕",
    shortLabel: "代代木上原BOLT",
    desc: "代代木上原必去！可帶狗的時尚咖啡空間，手沖咖啡＆自家烘焙甜點",
    tag: "東京",
    emoji: "☕",
    image: "/bolt-uehara/bolt-1.jpg",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "isehara-gelato",
    category: "cafe",
    name: "伊勢原義式冰淇淋推薦｜石田牧場めぐり・神奈川人氣甜點🍦",
    shortLabel: "伊勢原ジェラート",
    desc: "牧場直送鮮牛奶！神奈川伊勢原必吃ジェラート，CP值超高的隱藏名店",
    tag: "神奈川",
    emoji: "🍦",
    image: "/isehara-gelato/meguri-1.jpg",
    areas: ["其他"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "daikanyama-cafe",
    category: "cafe",
    name: "代官山咖啡廳推薦4選｜義式烘焙・甜點・可頌・自家烘焙☕",
    shortLabel: "代官山咖啡",
    desc: "米蘭義式烘焙PRINCI・星級甜點DOLCE TACUBO・法式可頌Doré・自家烘焙DUCT COFFEE LAB",
    tag: "東京",
    emoji: "☕",
    image: "/daikanyama-cafe/princi-1.jpg",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-09-03",
  },
  {
    slug: "nakameguro-cafe",
    category: "cafe",
    name: "中目黑咖啡廳推薦2選｜星巴克臻選烘焙工坊・世界冠軍拉花☕",
    shortLabel: "中目黑咖啡",
    desc: "隈研吾設計的星巴克臻選，加上拉花世界冠軍的STREAMER，走路6分鐘串一條",
    tag: "東京",
    emoji: "☕",
    image: "/nakameguro-cafe/starbucks-1.jpg",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-09-03",
  },
  {
    slug: "shimokitazawa-cafe",
    category: "cafe",
    name: "下北澤咖啡廳推薦4選｜東京必去人氣美食＆甜點☕",
    shortLabel: "下北澤咖啡",
    desc: "純素烘焙・起司蛋糕・自家焙煎・BONUS TRACK，下北澤必去人氣店",
    tag: "東京",
    emoji: "☕",
    image: "/shimokitazawa-cafe/vegan-1.jpg",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "kobe-cafe",
    category: "cafe",
    name: "神戶咖啡推薦4選｜教堂咖啡・異人館・巧克力老店☕",
    shortLabel: "神戶咖啡",
    desc: "教堂改建咖啡廳・北野異人館洋館咖啡・熊熊麵包吃到飽・Caffarel義大利巧克力，神戶必去4間人氣店",
    tag: "兵庫",
    emoji: "☕",
    image: "/kobe-cafe/caffarel-3.jpg",
    areas: ["兵庫"],
    published: "2026-07-01",
    updated: "2026-08-13",
  },
  {
    slug: "shukugawa",
    category: "cafe",
    name: "夙川咖啡廳推薦2選｜法式可麗餅＆精品咖啡☕",
    shortLabel: "夙川咖啡",
    desc: "クレープリー・ルポ＆ゆげ焙煎所，關西必去咖啡廳",
    tag: "兵庫",
    emoji: "☕",
    image: "/shukugawa/crepe-1.jpg",
    areas: ["兵庫"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "cafe",
    category: "cafe",
    name: "自由之丘咖啡店推薦｜東京必去咖啡散步地區☕",
    shortLabel: "自由之丘咖啡",
    desc: "貝果・義式冰淇淋・起司披薩，3間人氣店實際走訪",
    tag: "東京",
    emoji: "☕",
    image: "/cafe/gelato-1.jpg",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "chigasaki",
    category: "spot",
    name: "茅崎夏日推薦｜湘南海灘野餐＆清晨6點開門的海邊咖啡🌊",
    shortLabel: "茅崎湘南海灘",
    desc: "東京出發1小時！看烏帽子岩與江之島的海灘野餐＋海邊咖啡tuckshop的手作司康",
    tag: "神奈川",
    emoji: "🌊",
    image: "/chigasaki/cover.jpg",
    areas: ["其他"],
    published: "2026-08-18",
    updated: "2026-08-18",
  },
  {
    slug: "kobe-herb-garden",
    category: "spot",
    name: "神戶布引香草園推薦｜纜車空中散步・花海與夜景🌿",
    shortLabel: "神戶布引香草園",
    desc: "搭纜車登上400m山頂！四季花海・古堡建築・神戶港夜景，從新神戶駅直達",
    tag: "兵庫",
    emoji: "🌿",
    image: "/kobe-herb-garden/cover.jpg",
    areas: ["兵庫"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "shirahama",
    category: "spot",
    name: "和歌山白浜景點推薦4選｜動物樂園・海邊露營・海景咖啡・海鮮BBQ🐬🌊",
    shortLabel: "和歌山白浜",
    desc: "冒險大世界看海豚表演・志原海岸豪華露營・かげろう海景咖啡・とれとれ市場海鮮BBQ，關西度假必去",
    tag: "和歌山",
    emoji: "🐼",
    image: "/shirahama/cover.jpg",
    areas: ["其他"],
    published: "2026-07-01",
    updated: "2026-08-18",
  },
  {
    slug: "artbar-tokyo",
    category: "spot",
    name: "東京畫畫體驗推薦｜Artbar Tokyo・喝酒作畫的大人藝術體驗🎨",
    shortLabel: "Artbar Tokyo",
    desc: "一邊喝紅酒一邊畫畫的Paint & Sip體驗！初學者也OK・手ぶら參加，原宿・代官山分店",
    tag: "東京",
    emoji: "🎨",
    image: "/artbar-tokyo/artbar-1.jpg",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "ajisai",
    category: "spot",
    name: "東京繡球花景點推薦2選｜台場シンボルプロムナード＆文京白山神社紫陽花🌸",
    shortLabel: "東京繡球花景點",
    desc: "6月限定！免費入場的東京都心紫陽花景點・台場散步道＆白山神社文京あじさいまつり",
    tag: "東京",
    emoji: "🌸",
    image: "/ajisai/cover.jpg",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "katsunuma",
    category: "spot",
    name: "山梨勝沼＆石和溫泉一泊二日｜葡萄鄉美食・酒莊・採桃🍇🍑",
    shortLabel: "山梨勝沼＆石和溫泉",
    desc: "東京近郊葡萄酒故鄉！銀月食堂・Château Mercian酒莊・石和溫泉ホテル甲子園・あすなろ園採桃・信玄餅・鳥もつ煮",
    tag: "山梨",
    emoji: "🍇",
    image: "/katsunuma/cover.jpg",
    areas: ["其他"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "tokyo-disney-around",
    category: "spot",
    name: "東京迪士尼周邊玩法｜不進園也能玩！度假區線一日券＆イクスピアリ美食🎢",
    shortLabel: "東京迪士尼周邊",
    desc: "Disney Resort Line一日券・可愛車廂＆CAFÉ AUX BACCHANALES法式咖啡廳",
    tag: "東京",
    emoji: "🎢",
    image: "/tokyo-disney-around/cover.jpg",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-08-12",
  },
  {
    slug: "skytree",
    category: "spot",
    name: "東京晴空塔攻略｜門票預約、交通方式、夜景與拍照景點整理🌃",
    shortLabel: "東京晴空塔",
    desc: "Tokyo Skytree展望台・夜景・玻璃地板＆東京ソラマチ周邊整理",
    tag: "東京",
    emoji: "🌃",
    image: "/skytree/cover.png",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-08-12",
  },
  {
    slug: "rokko-arima",
    category: "spot",
    name: "六甲山健行推薦｜神戶登山＆有馬溫泉一日遊🏔️♨️",
    shortLabel: "六甲山＆有馬溫泉",
    desc: "登山＋纜車＋有馬溫泉＋人氣ジェラート，關西自然＆溫泉完美行程",
    tag: "兵庫",
    emoji: "🏔️",
    image: "/rokko-arima/rokko-1.jpg",
    areas: ["兵庫"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "ine",
    category: "spot",
    name: "京都伊根町觀光推薦｜舟屋村絕景・咖啡＆住宿🏘️",
    shortLabel: "京都伊根町",
    desc: "日本最美村落「伊根舟屋」！INE CAFE咖啡＆仁風荘住宿完整指南",
    tag: "京都",
    emoji: "🏘️",
    image: "/ine/town-1.jpg",
    areas: ["其他"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "shodoshima",
    category: "spot",
    name: "小豆島景點推薦6選｜橄欖公園・魔女宅急便・醬油村🫒",
    shortLabel: "小豆島",
    desc: "神戶搭渡輪3.5小時直達！橄欖公園免費借魔法掃帚・懷舊營養午餐・醬油霜淇淋",
    tag: "香川",
    emoji: "🫒",
    image: "/shodoshima/olive-1.jpg",
    areas: ["四國"],
    published: "2026-09-04",
    updated: "2026-09-04",
  },
  {
    slug: "kochi",
    category: "spot",
    name: "高知觀光推薦3選｜四國必去仁淀藍秘境・鰹魚タタキ・ひろめ市場🌊",
    shortLabel: "高知觀光",
    desc: "夢幻仁淀藍秘境＆鰹魚炙烤體驗＆ひろめ市場美食，四國高知一日遊",
    tag: "高知",
    emoji: "🌊",
    image: "/kochi/nikobuchi-1.jpg",
    areas: ["四國"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "kagawa",
    category: "spot",
    name: "香川觀光推薦5選｜烏龍麵縣美食・水族館・金刀比羅宮🍜",
    shortLabel: "香川觀光",
    desc: "讚岐烏龍麵名店＆四國水族館＆金刀比羅宮，烏龍麵縣完整指南",
    tag: "香川",
    emoji: "🍜",
    image: "/kagawa/yamagoe-1.jpg",
    areas: ["四國"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "hikone",
    category: "spot",
    name: "彥根城觀光推薦｜滋賀必去國寶城・吉祥物彥根貓🏯",
    shortLabel: "彥根城",
    desc: "日本國寶彥根城＋人氣吉祥物彥根貓＋江戶城下町散步",
    tag: "滋賀",
    emoji: "🏯",
    image: "/hikone/castle-1.png",
    areas: ["其他"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "utsunomiya",
    category: "spot",
    name: "宇都宮觀光推薦3選｜栃木必去竹林・餃子・神社🎋",
    shortLabel: "宇都宮觀光",
    desc: "夢幻竹林・餃子巡禮・能量神社，東京近郊一日遊隱藏寶地",
    tag: "栃木",
    emoji: "🎋",
    image: "/utsunomiya/wakayama-1.jpg",
    areas: ["其他"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "showa-kinen-park",
    category: "spot",
    name: "昭和紀念公園推薦｜東京立川散步必去・四季絕景🌿",
    shortLabel: "昭和記念公園",
    desc: "東京最大級的國營公園！春櫻・夏向日葵・秋紅葉・冬燈光秀",
    tag: "東京",
    emoji: "🌿",
    image: "/showa-kinen-park/park-1.jpg",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "kamikochi",
    category: "spot",
    name: "上高地＆奧飛騨旅行推薦4選｜日本阿爾卑斯絕景🏔️",
    shortLabel: "上高地",
    desc: "河童橋・平湯大瀑布・新穂高纜車・奧飛騨溫泉飯店，自然療癒之旅",
    tag: "其他",
    emoji: "🏔️",
    image: "/kamikochi/cover.jpg",
    areas: ["其他"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "tokyo-tower",
    category: "spot",
    name: "東京鐵塔推薦｜東京必去地標・夜景景點🗼",
    shortLabel: "東京鐵塔",
    desc: "333公尺東京象徵！主展望台＆頂層展望台夜景超震撼",
    tag: "東京",
    emoji: "🗼",
    image: "/tokyo-tower/tower-1.jpg",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "ueno-zoo",
    category: "spot",
    name: "上野動物園推薦｜東京必去親子景點・門票¥600🐘",
    shortLabel: "上野動物園",
    desc: "日本最古老的動物園，門票¥600，亞洲象與小熊貓・親子旅行推薦",
    tag: "東京",
    emoji: "🐼",
    image: "/ueno-zoo/zoo-1.jpg",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-08-18",
  },
  {
    slug: "museum",
    category: "spot",
    name: "東京美術館推薦｜國立新美術館＆根津美術館2選🎨",
    shortLabel: "東京美術館",
    desc: "六本木現代建築・表參道日本庭園，2間必去美術館完整指南",
    tag: "東京",
    emoji: "🎨",
    image: "/museum/nact-1.jpg",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "koyo",
    category: "spot",
    name: "東京紅葉推薦｜神宮外苑銀杏並木の金黃大道🍁",
    shortLabel: "東京紅葉",
    desc: "約300公尺的金黃銀杏隧道，東京秋天最具代表性的景點",
    tag: "東京",
    emoji: "🍁",
    image: "/koyo/gaien-1.jpg",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "spot",
    category: "spot",
    name: "東京野餐推薦3選｜新宿御苑・代代木・日比谷公園🌿",
    shortLabel: "東京野餐",
    desc: "草地・拍照・放鬆，東京最受歡迎3大野餐公園完整指南",
    tag: "東京",
    emoji: "📍",
    image: "/spot/shinjuku-1.jpg",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "hakone",
    category: "spot",
    name: "箱根一日遊推薦｜從東京搭浪漫特快出發🚃",
    shortLabel: "箱根一日遊",
    desc: "美術館・足湯・神社・甜點，一天玩遍箱根精華",
    tag: "箱根",
    emoji: "♨️",
    image: "/hakone/shrine-1.jpg",
    areas: ["其他"],
    published: "2026-07-01",
    updated: "2026-08-12",
  },
  {
    slug: "hokkaido",
    category: "spot",
    name: "北海道自由行必去景點10選｜札幌・小樽・富良野一次玩遍",
    shortLabel: "北海道自由行",
    desc: "音樂盒堂・青池・薰衣草花田・迴轉壽司・成吉思汗，北海道精華全收錄",
    tag: "北海道",
    emoji: "🗾",
    image: "/hokkaido/farm-1.jpg",
    areas: ["北海道"],
    published: "2026-07-01",
    updated: "2026-07-21",
  },
  {
    slug: "haneda-airport-access",
    category: "prep",
    name: "羽田機場到東京交通攻略 2026｜京急、單軌電車、巴士、計程車的價錢與時間✈️",
    shortLabel: "羽田機場交通",
    desc: "京急¥330・單軌¥520・巴士¥1,300・定額計程車¥6,900起。首末班車、深夜抵達、各區域最佳路線",
    tag: "機場交通",
    emoji: "✈️",
    image: "/haneda-airport-access/cover.png",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-09-07",
  },
  {
    slug: "narita-airport-access",
    category: "prep",
    name: "成田機場到東京市區交通攻略｜Skyliner、巴士、JR、行李配送怎麼選？🚄",
    shortLabel: "成田機場交通",
    desc: "成田機場到東京市區交通完整指南！Skyliner・NEX・機場巴士・包車・行李配送・前泊比較",
    tag: "機場交通",
    emoji: "🚄",
    image: "/narita-airport-access/cover.png",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-08-12",
  },
  {
    slug: "taiwan-japan-guide",
    category: "prep",
    name: "台灣飛日本自由行攻略｜機票、網路卡、換日幣與退稅新制✈️",
    shortLabel: "台灣飛日本攻略",
    desc: "桃園松山飛東京大阪怎麼選、悠遊卡能不能用、日幣何時換、2026年11月退稅新制",
    tag: "台灣出發",
    emoji: "🇹🇼",
    image: "/taiwan-japan-guide/cover.png",
    areas: ["東京", "大阪"],
    published: "2026-08-18",
    updated: "2026-08-18",
  },
  {
    slug: "hongkong-japan-guide",
    category: "prep",
    name: "香港去日本自由行攻略｜機票、上網卡、日圓兌換與退稅新制✈️",
    shortLabel: "香港去日本攻略",
    desc: "香港飛東京大阪點揀、八達通用唔到、上網卡點買、2026年11月退稅新制",
    tag: "香港出發",
    emoji: "🇭🇰",
    image: "/hongkong-japan-guide/cover.png",
    areas: ["東京", "大阪"],
    published: "2026-08-18",
    updated: "2026-08-18",
  },
  {
    slug: "japan-esim",
    category: "prep",
    name: "日本自由行 eSIM 使用指南｜抵達日本就能上網的事前準備📱",
    shortLabel: "日本eSIM指南",
    desc: "eSIM 使用方式＆與實體 SIM／租借 Wi-Fi 比較。出發前先安心搞定上網",
    tag: "上網準備",
    emoji: "📱",
    image: "/japan-esim/cover.png",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-08-12",
  },
  {
    slug: "tokyo-subway-ticket",
    category: "prep",
    name: "東京地鐵24/48/72小時乘車券｜Tokyo Subway Ticket購買與使用方式🚇",
    shortLabel: "東京地鐵24/48/72小時券",
    desc: "東京自由行交通指南！地下鐵周遊券完整解說，附行程範例與選購建議",
    tag: "交通票券",
    emoji: "🚇",
    image: "/tokyo-subway-ticket/cover.png",
    areas: ["東京"],
    published: "2026-07-01",
    updated: "2026-08-12",
  },
];

export const ARTICLE_BY_SLUG: Record<string, Article> = Object.fromEntries(
  ARTICLES.map((a) => [a.slug, a])
);

export type PickItem = Article & { href: string };

/** カテゴリ別（トップページ用）。順序は ARTICLES の並び順を保つ。 */
export const picks: Record<string, PickItem[]> = ARTICLES.reduce(
  (acc, a) => {
    (acc[a.category] ||= []).push({ ...a, href: `/${a.slug}` });
    return acc;
  },
  {} as Record<string, PickItem[]>
);

/**
 * 関連記事を自動選出する。
 * 同じ地域タグ＞同じエリア＞同じカテゴリ の順で優先し、足りなければ新しい記事で埋める。
 */
/** 決定的（ビルドごとに変わらない）な擬似乱数。関連記事の並び分散に使う。 */
function hash(str: string): number {
  let h = 2166136261;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

export function getRelatedArticles(
  slug: string,
  { limit = 8, exclude = [] as string[] } = {}
): Article[] {
  const current = ARTICLE_BY_SLUG[slug];
  if (!current) return [];
  const excluded = new Set([slug, ...exclude.map((s) => s.replace(/^\//, ""))]);

  const score = (a: Article) => {
    let s = 0;
    if (a.tag === current.tag) s += 4;
    if (a.areas.some((x) => current.areas.includes(x))) s += 2;
    if (a.category === current.category) s += 3;
    return s;
  };

  // 同スコア内は「記事ごとに違う順序」で並べ、特定の記事だけがリンクを独占しないようにする
  return ARTICLES.filter((a) => !excluded.has(a.slug))
    .map((a) => ({ a, s: score(a), r: hash(slug + a.slug) }))
    .sort((x, y) => y.s - x.s || x.r - y.r)
    .slice(0, limit)
    .map((x) => x.a);
}

/** フッターのリンク集も記事登録から自動生成する（追加忘れを防ぐ） */
export const FOOTER_GROUP_ORDER = [
  "美食・拉麵",
  "咖啡廳",
  "東京景點",
  "近郊・地方景點",
  "伴手禮・零食",
  "出發前準備",
] as const;

export type FooterGroup = (typeof FOOTER_GROUP_ORDER)[number];

export const FOOTER_GROUP_ICON: Record<FooterGroup, string> = {
  "美食・拉麵": "🍜",
  "咖啡廳": "☕",
  "東京景點": "🗼",
  "近郊・地方景點": "🏔️",
  "伴手禮・零食": "🍩",
  "出發前準備": "🎒",
};

export function footerGroupOf(a: Article): FooterGroup {
  if (a.category === "prep") return "出發前準備";
  if (a.category === "snacks") return "伴手禮・零食";
  if (a.category === "cafe") return "咖啡廳";
  if (a.category === "ramen") return "美食・拉麵";
  return a.areas.includes("東京") ? "東京景點" : "近郊・地方景點";
}

export const footerGroups: { title: FooterGroup; icon: string; links: Article[] }[] =
  FOOTER_GROUP_ORDER.map((title) => ({
    title,
    icon: FOOTER_GROUP_ICON[title],
    links: ARTICLES.filter((a) => footerGroupOf(a) === title),
  })).filter((g) => g.links.length > 0);
